### ISSUE TITLE
Design and develop minimum frontend code

### ISSUE THREAD

**Issue by SebastianZimmeck** [Wesleyan-Media-Project/creative-app#1]
As we just discussed, @candace-walker and @atlasharry will start developing frontend code --- start with vanilla HTML, CSS, JS --- for processing csv data. The code takes as input a csv file, surfaces some UI to the user (e.g., a button or selector), and displays the data in the browser.

@markusneumann provided an [example](https://mediaproject.wesleyan.edu/releases-102920/#fig1) of how the UI could look like and what its functionality could be.

For the time being, the code can just run locally in the browser (i.e,, right-click on the entry index.html file and select display in browser). We can webify it later as necessary.

It there are libraries that help doing the job, especially, for processing csv files, let's use those.

@pvo70, could you post a minimum working example file here?

**Comment by markusneumann** [comment]
For the map: If you right-click the web page and then do 'View Page Source', you can search for the html code of the map. It's on line 789. Here's the direct link to it: [https://wesmedia.wesleyan.edu/Images/2020_advantage_map/AdvantageChoropleth_oct27.html](https://wesmedia.wesleyan.edu/Images/2020_advantage_map/AdvantageChoropleth_oct27.html) To actually make the map, you also need two csvs and a json file that contain the underlying data. The dropdown menu of the map determines which csv file it references. I will share those files on Slack.

**Comment by atlasharry** [comment]
I have updated a draft code covering CSV files into an HTML table. Some issues with this code are 

1: I used the built-in Fetch API to read the CSV files locally. For security reasons, Chrome blocked local files by CORS policy. To fix this and run the HTML code, add the following to the launch flags.: 

> "...\chrome.exe" --allow-file-access-from-files --allow-file-access --allow-cross-origin-auth-prompt  


2: The header title seems to not match perfectly with the content. I tried to add some blank space between titles, but issues remain because the content on each cell varies in length.

**Comment by atlasharry** [comment]
At the same time, we have started self-learning some fundamental knowledge of html+css+js systematically. But I am still a little overwhelmed by all of those different APIs, methods, and commands.

**Comment by SebastianZimmeck** [comment]
> Or only allow the table to be use for parsing specific element to return to the user at their request?

This would be better.

> Is only one specific cell or an entire row/ column?

In principle, we want to allow the user to query whatever they want (one row, one column, two rows, once cell, ...).

**Comment by SebastianZimmeck** [comment]
@candace-walker and @atlasharry, here seems to be a good starting point: [data2csv](https://github.com/prof3ssorSt3v3/data-2-csv). This is not exactly what we need, but a stub that you can start to explore. You can simply run it locally in browser.

<img width="685" alt="Screenshot 2023-03-06 at 7 34 36 PM" src="https://user-images.githubusercontent.com/11034003/223288307-4acbff45-6481-4896-9b0e-d11af1b77a34.png">

Here is the [related tutorial video](https://www.youtube.com/watch?v=MsHrntNF0Z0) if helpful. 

So, try to understand how this example works (and possibly start modifying for our purposes).

Note this example does not require any server. It works purely locally. We had discussed setting up a simple web app with a server, database, etc. via [InfinityFree](https://www.infinityfree.net/). But for the time being, we can leave everything local.

**Comment by SebastianZimmeck** [comment]
Here is a sample [csv file](https://drive.google.com/file/d/1fMn6Rhqs8bWgu0S0vpSZqevHnfajQWSE/view?usp=sharing_eip_m&ts=6418bb8c).

**Comment by IneshV** [comment]
Since I've used InfinityFree, I think it would make sense for me to to get started making the web app.  Setting up a server and database there seems doable and then I'll try to figure out how to manipulate the data there.

**Comment by SebastianZimmeck** [comment]
> I think it would make sense for me to to get started making the web app.

Sure, feel free to experiment. For context, we are currently in an exploratory phase and have not settled on any architecture, technologies, or even features that our site should have. Over the next few weeks the picture will clarify.

@candace-walker and @atlasharry are looking into taking a csv file and displaying (parts of) it locally via a browser. One point to note here is that this setup entails some limitations: 
- For example, if the csv file is large, say, a million lines with 50 columns, we may hit a storage limit as all data would need to be processed entirely through the DOM (if I see that correctly). 
- Another limitation may be that we would need to rewrite program logic for basic searching and sorting that is already inherently available to via the csv formatting. We may just manually copy the data into a Google Sheet. We could display it in an iFrame having it pop up in a separate tab for closer interaction, along the lines [here](https://www.groovypost.com/howto/embed-a-google-sheet-in-a-website/).

@atlasharry and @candace-walker, can you look into these points? 

As a general guideline, we should try to leverage as much as possible existing tools because we are just looking for standard functionality, and it is is also not at the core of our project to have the most polished UI. Maybe, even a static site is sufficient with [GitHub Pages](https://pages.github.com/), maybe with a custom URL. 

Here is a mockup of our project site how I currently envision it. 

<img src="https://user-images.githubusercontent.com/11034003/226672843-932abc43-bde3-4431-bee1-51fdce671167.jpg" width="700" />

@markusneumann and @pvo70, what are your thoughts? Can you help refining the vision (e.g., which technologies to use, what features do we need, etc.)?

**Comment by candace-walker** [comment]
Okay, I'll look at this further and it may be helpful for us to go over this design project in the meeting tomorrow.

**Comment by SebastianZimmeck** [comment]
FYI on the discussion of Python for the Web.
- [PyVibe](https://www.pyvibe.com/)
- [Related Hacker News thread](https://news.ycombinator.com/item?id=35255052)

**Comment by candace-walker** [comment]
Meeting just finished, my task breakdown is:
-- Documenting the index, css, and js files
-- Implement user inputed change in csv (search/sort) using current html structure
-- Looking into incorporating Node.js/ Express.js for page updating/ listening feature
We have a follow-up meeting Saturday

**Comment by atlasharry** [comment]
-- I will look into another structure approach using Google Sheets and iFrame to represent our data.

**Comment by IneshV** [comment]
Just made an infinity free folder with my code and the website is now up. Here is the link:  https://wmp-creative.infinityfreeapp.com. The form is very basic right now so if Candace and Harry could add some of their aesthetic html work to the bottom of the index file: https://github.com/Wesleyan-Media-Project/creative-frontend/blob/main/infinityfree/index.php it could go a long way.

**Comment by IneshV** [comment]
[SQL_Tutorial.md](https://github.com/Wesleyan-Media-Project/creative-frontend/files/11070022/SQL_Tutorial.md)
Here is Sebastian's tutorial so you can better understand infinity free.

**Comment by atlasharry** [comment]
I have uploaded a draft UI with Google Sheets integrated using Iframe. There is also a button to open the sheet in a separate tab so the user can see the data more clearly. 
However, there are a few remaining issues that I am currently working on:

> 1: Due to Google Sheets' 10MB file size limitation, presenting data sets larger than 14 million is not possible. I am exploring ways to bypass this limitation, but it's likely that we'll need to use Google Sheets for smaller files and find an alternative solution to display the larger files.

>2: Users can currently use the built-in browser search function (Ctrl+F) to find specific data. However, sorting is not supported within the iFrame-embedded Google Sheets. One solution is to process data through DOM using the original JS way. Alternatively, we could request search or sort functionality through the back-end server and present the results to the user if processing through DOM causes memory issues.

**Comment by atlasharry** [comment]
**Also, here is a screenshot of the draft site:**
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/104949958/227742859-de4f798a-a846-40d1-9ba1-2f511bdb082d.png">


> I have uploaded a draft UI with Google Sheets integrated using Iframe. There is also a button to open the sheet in a separate tab so the user can see the data more clearly. However, there are a few remaining issues that I am currently working on:
> 
> > 1: Due to Google Sheets' 10MB file size limitation, presenting data sets larger than 14 million is not possible. I am exploring ways to bypass this limitation, but it's likely that we'll need to use Google Sheets for smaller files and find an alternative solution to display the larger files.
> 
> > 2: Users can currently use the built-in browser search function (Ctrl+F) to find specific data. However, sorting is not supported within the iFrame-embedded Google Sheets. One solution is to process data through DOM using the original JS way. Alternatively, we could request search or sort functionality through the back-end server and present the results to the user if processing through DOM causes memory issues.

**Comment by SebastianZimmeck** [comment]
As we discussed today, we converged on exploring the LAMP stack. @candace-walker and @atlasharry will clean up their code to a reasonable degree, document it, and push it. Then we can move on and close this issue.
