### ISSUE TITLE
Explore cloud providers for building creative app

### ISSUE THREAD

**Issue by SebastianZimmeck** [Wesleyan-Media-Project/creative-app#3]
As discussed today, we may deploy a [LAMP](url) stack with some cloud provider. Which one should it be?

Let's assume for the time being that we have 1,000 people using our site per month, each making 10 queries to the database. We have permanently stored 3GB (just to have something to work off; if I am completely off here, everyone, please chime in). 

Some options are:
- [InfinityFree](https://www.infinityfree.net/): Simple provider, but why not. A good starting point. How far do we get with the free tier? How much for the paid tier.
- [Heroku](https://www.heroku.com): Would have been my preferred choice but does not have a free tier anymore. There is a [student free tier](https://www.heroku.com/github-students), though, if anyone wants to explore.
- [Free Heroku alternatives Hacker News thread](https://news.ycombinator.com/item?id=33300053): Some [very good suggestions](https://news.ycombinator.com/item?id=33300653), especially, [alwaysdata](https://www.alwaysdata.com/en/)
- [Netlify](https://www.netlify.com/): Similar to Heroku, but I do not know much more about it.
- [Glitch](https://glitch.com/): Also, similar to Heroku. I always find it a bit unintuitive to use, though.
- [Google Cloud](https://cloud.google.com/) and [Firebase](https://firebase.google.com/), which is running on top of Google Cloud: Getting complexer.
- [AWS](https://aws.amazon.com/): pretty complex; never really got into it.
- [Pynecone](https://pynecone.io/): for Python + SQL (but no hosting; only self-hosting at the moment?)

If anyone has other suggestions, please feel free to add. 

@candace-walker and @atlasharry are taking the lead on this with @IneshV helping out as it comes to InfinityFree. Though, it is probably a good idea if everyone just starts with InfinityFree.

**Comment by candace-walker** [comment]
Okay, got it. I'll make sure to start with InfinityFree first.

**Comment by atlasharry** [comment]
Got it! I will also start by exploring InfinityFree first.

**Comment by SebastianZimmeck** [comment]
We are using @sheoftensaid's infrastructure.
