### ISSUE TITLE
Design app architecture

### ISSUE THREAD

**Issue by SebastianZimmeck** [Wesleyan-Media-Project/creative-app#7]
As discussed today in our call I am opening this issue to design and converge on an overall system architecture.

Please, everyone, chime in by providing new comments or editing this comment. Particularly, @pvo70, @markusneumann, and @jyao01, your expertise on this would be much appreciated.  Particularly, filling in the repo links below to identify what we already have would be helpful.

<img src="http://mediaproject.wesleyan.edu/wp-content/uploads/2023/04/wmp_circle_pipeline.png">

### 1. Requirements

The requirements for the app are from our [NSF proposal](https://drive.google.com/file/d/1jD7corNzIpNUcsVi2O_2FPy01Lq8wFgT/view?usp=sharing). does not need to match exactly but deliver the core functionality and also diverge wherever necessary, e.g., technological reasons.

#### 1.1 Acquiring Digital Advertising Data Across Platforms

Data will be acquired from Google and Facebook (only if bandwidth going beyond, e.g., considering Snapchat and Twitter).

Product deliverables of this aim are: (a) Acquisition scripts and their documentation, and (b) a repo of candidates and elected federal office holders.

| Scripts for data types to acquire                                                                              | Repo  link      |
| -------------                                                                                                              | ------------- |
| Creative content                                                                                                                          |  ?  |
| Spending data                                                                                                                             |  ?  |
| Impression (countable amount of times an ad is seen/fetched to be viewed (not clicks))                                                                                            |  ?  |
| Sponsors by type (e.g., candidates, outside groups, political parties)                                  |  ?  |
| Sponsor names and other sponsor data                                                                                   |  ?  |
| Candidate/office holder names, profile pictures, and other candidate/office holder data   |  [1](https://github.com/Wesleyan-Media-Project/face_url_scraper_2022.git)  |

Comments:
- Run scripts repeatedly
   
#### 1.2. Processing and Integrating Data Through Human and Computational Methods as a Service to the Public

Product deliverables of this aim are (a) processing scripts and their documentation, and (b) the CREATIVE web app to visualize and display data.

| CREATIVE App features and scripts with respective functionality                              | Repo link        |
| -------------                                                                                                                     | ------------- |
| Link data, particularly, cross-platform                                                                                              |  ?  |
| Expandable to be used for 2024 presidential cycle and beyond                                                    |  ?  |
| Duplicate content identification                                                                                                         |  ?  |
| Textual, image, and video processing                                                                                               |  [1](https://github.com/Wesleyan-Media-Project/fb_2022.git),[2](https://github.com/Wesleyan-Media-Project/google_2022.git)  |
| Facial recognition procedures to identify and validate candidate references                               |  [1](https://github.com/Wesleyan-Media-Project/fb_2022.git),[2](https://github.com/Wesleyan-Media-Project/google_2022.git)|
| Text methods to identify and validate candidate references                                                        |  [1](https://github.com/Wesleyan-Media-Project/entity_linking),[2](https://github.com/Wesleyan-Media-Project/entity_linking_2022)  |
| Human content coding procedures, documentation, intercoder reliability scoring                      |  [link](https://github.com/Wesleyan-Media-Project/human_coding_2022)  |
| Classification models, documentation, and comparisons of model performance                         |  [1](https://github.com/Wesleyan-Media-Project/party_classifier),[2](https://github.com/Wesleyan-Media-Project/ad_goal_classifier),[3](https://github.com/Wesleyan-Media-Project/ad_tone),[4](https://github.com/Wesleyan-Media-Project/issue_classifier),[5](https://github.com/Wesleyan-Media-Project/attack_like),[6](https://github.com/Wesleyan-Media-Project/party_classifier_pdid),[7](https://github.com/Wesleyan-Media-Project/ABSA)  |
| Final, cleaned versions of sponsor-level, election ad-level, and candidate mention-level data   |  ?  |

Comments:
- Integration with OpenSecrets to match sponsors across platforms, to incorporate linking information, and to using automatic matching methods along with manual verification 
- Facebook’s ad library and data files are keyword searchable, but multiple versions of candidate names and candidates with common names all pose issues, and image data is not searchable. Google’s ad content is not keyword searchable and therefore requires extraction and processing to perform the same types of content filtering. In addition, advertising that pictures but does not mention a candidate would require image and video processing.
- We anticipate that the data will be used by academics, journalists, policymakers, practitioners, educators, and the general public
- Manual input data at the backend; no automatic update of database
- We will provide high-quality, labeled textual and audiovisual data that will be made accessible to researchers to potentially facilitate breakthroughs in AI - by providing labeled training data 

#### 1.3 Initial Sketch of the CREATIVE Web App
 
<img width="640" alt="Screenshot 2023-04-03 at 6 54 50 PM" src="https://user-images.githubusercontent.com/11034003/229644063-b7d287bd-20d0-4e65-9e1f-86231e92fbb6.png">

Comments:
- We can use any technologies we like, modify features, ...

### 2. Translating Requirements into App Architecture, Features, and Technologies

Here is an idea as a starting point and context for the CREATIVE app:

We create a [landing page](https://en.wikipedia.org/wiki/Landing_page) as entry point to the CREATIVE project. The landing page can be based on  [GitHub Pages](https://pages.github.com/), which is free. We can get a custom domain, e.g., via Google Domains, for maybe, \$15/year. Here are some examples for GitHub Pages with custom domains: https://privacytechlab.org/, https://globalprivacycontrol.org/

The landing page has links to the various repos and explains how they are connected. The repos themselves have then detailed documentation on their particular content in their readmes. We include general information about the project, news, ...

The landing page also includes a link to the CREATIVE app. The CREATIVE app is hosted and visualized via Google Looker, a LAMP stack on some cloud provider service, ... The readme in the repo of the CREATIVE app (this repo) explains how to deploy it.

Important considerations for picking the tech stack are:
- Costs
- Maintainability (i.e., pick proven technology easy to maintain and properly supported) 
- Extensibility
- Open source (though, we certainly can build on proprietary technology; we just need to open-source what we develop)

### 3. General Considerations

If we are not able to build everything, we should rank the functionality and build the core functionality we identify.
If there are features missing, please feel free to add or modify.
I gave everyone access to a [Google Drive folder](https://drive.google.com/drive/folders/1Bkllj4CMy-G7kRfrH34uVw5rX-5_em4Z?usp=sharing) to store text documents, spreadsheets, etc. If you are creating any such document, please store it there so that we have a central place to which everyone has access.

**Comment by IneshV** [comment]
Here is the link to the code I used to create a possible template: https://github.com/IneshV/IneshV.github.io/blob/master/blog/index.html
<img width="1440" alt="Screen Shot 2023-04-10 at 4 05 35 PM" src="https://user-images.githubusercontent.com/123998765/230987998-be01637c-8397-47f4-bd59

<img width="1440" alt="Screen Shot 2023-04-10 at 4 05 51 PM" src="https://user-images.githubusercontent.com/123998765/230988043-1be2492d-aa38-4ac4-87ed-5dd176c99876.png">
-54f848848293.png">

**Comment by atlasharry** [comment]
I have explored [Echart](https://echarts.apache.org/en/index.html) this week.

- Echart is an open-source JavaScript visualization library under Apache, so there won't be any issues with our open-code policy.
- According to their [introduction](https://echarts.apache.org/en/feature.html), Echart can switch between Canvas and SVG rendering. With progressive rendering and stream loading, it might be possible to render 10 million data points in real-time, making it capable of displaying visualizations with tens of millions of data points.
![image](https://user-images.githubusercontent.com/104949958/232341377-1f3a9fdd-d94d-48c3-bcaa-ef5568f30cad.png)

- Use this [link](https://github.com/apache/echarts/tree/5.4.2/dist) to install Echart. In most cases, I found the file "[echarts.min.js](https://github.com/apache/echarts/blob/5.4.2/dist/echarts.min.js)" to be sufficient.
- In some examples they provided, data is directly entered into the [code](https://echarts.apache.org/examples/en/editor.html?c=pie-simple) like this:
>  name: 'Access From',
      type: 'pie',
      radius: '50%',
      data: [
        { value: 1048, name: 'Search Engine' },
        { value: 735, name: 'Direct' },
        { value: 580, name: 'Email' },
        { value: 484, name: 'Union Ads' },
        { value: 300, name: 'Video Ads' }
      ],
      emphasis: {
        itemStyle: {
          shadowBlur: 10,
          shadowOffsetX: 0,
          shadowColor: 'rgba(0, 0, 0, 0.5)'
        }

- However, it is also possible to read the data from a web server like this:
![image](https://user-images.githubusercontent.com/104949958/232344351-beca5a21-784f-455e-89c0-56dd7620820c.png)

- Similarily, it can load the data locally like this: 

> // Load CSV data from a local file
myChart.setOption({
    dataset: {
        source: './data.csv'
    },
    // ...
});

But then there will be issues with CORS policy :(

**Comment by IneshV** [comment]
https://docs.google.com/spreadsheets/d/1IvkZj9x8WU8v5LKGn1hhoUKeMc7xUTdM0_8MRZH_f3o/edit?usp=sharing 
We just finished meeting and here is a spreadsheet organizing each repo to one of the four given catagories

**Comment by candace-walker** [comment]
Hi y'all:
Here is a link for the organizer: https://docs.google.com/spreadsheets/d/1IvkZj9x8WU8v5LKGn1hhoUKeMc7xUTdM0_8MRZH_f3o/edit?usp=sharing
It's the link, but it has a second updated second sheet with the proposed flow changes

Then I created a visual: https://docs.google.com/drawings/d/1nDfH1BRPwJZuhtDS0R0W232XZicKG66_F29wT4DLjYY/edit?usp=sharing

**Comment by SebastianZimmeck** [comment]
As @sheoftensaid explained that our domain is registered via [DreamHost](https://www.dreamhost.com/), maybe we can deploy our app there as well. They [support MySQL, "Rails, Python, Javascript + more"](https://www.dreamhost.com/hosting/shared/#comparison-plans). Possibly, also an option ...

**Comment by sheoftensaid** [comment]
> As @sheoftensaid explained that our domain is registered via [DreamHost](https://www.dreamhost.com/), maybe we can deploy our app there as well. They [support MySQL, "Rails, Python, Javascript + more"](https://www.dreamhost.com/hosting/shared/#comparison-plans). Possibly, also an option ...

Also has the added benefit of no extra cost - our VPS is paid for through 3 years as it is where we host our WMP site.

**Comment by sheoftensaid** [comment]
You may have heard us refer to "the other pipeline graphic" during meetings - we thought it might be helpful to share it. As we've discussed, the process is not linear, so while this isn't a perfect representation, we hope it is helpful anyway.
<img src="https://mediaproject.wesleyan.edu/wp-content/uploads/2023/06/wmp_pipeline_111722_tabs.png">

**Comment by atlasharry** [comment]
I redraw some draft logos of "Creative" here: 
![1](https://github.com/Wesleyan-Media-Project/creative-app/assets/104949958/96e713aa-1df7-4850-8467-bf62a56feae0)
![2](https://github.com/Wesleyan-Media-Project/creative-app/assets/104949958/171ba7bd-2b22-449b-ab15-f837bbd1cb0a)
![3](https://github.com/Wesleyan-Media-Project/creative-app/assets/104949958/7849061c-8593-4eac-b063-9dfaebf42930)
![4](https://github.com/Wesleyan-Media-Project/creative-app/assets/104949958/87af64d8-8042-4dac-aca9-e0bb8bb90aee)

**Comment by candace-walker** [comment]
I added this in the slack last week, but I also wanted to document it the suggested logos here: https://docs.google.com/document/d/10AjRJxaBV-yx6cZdyHEU0eEVWINiUTnd7irsZ4A2wxQ/edit?usp=drive_link

**Comment by atlasharry** [comment]
I have audited the repo "fb_agg_reports_import" and "fb_ads_import" this week.

Regarding security risks, I don't think there are any sensitive information in the code(that will give other access to our database or something). In specific, in file: `fb_weekly_regions_import.R`, there is a section that contains sensitive information:

> conn = dbConnect(RMySQL::MySQL(), host="localhost",
                 user="xxxx", password="xxxx",
                 dbname="textsim_new")

In this place, the placeholder replaced the actual username and password.  Another minor issue is that there are lines that indicate the path directories like: `unzip(zipfile = df$fname[j],exdir = "/home/poleinikov/FB_reports/tmp").` This may give others a hint of the system architecture. (But I think it does not matter at all?)
Another approach to protecting sensitive information I can think of is to store sensitive information like usernames, passwords, and other credentials in environment variables, and access them from within the scripts. But the current approach is also perfectly fine.

I encountered some issues when I ran the file `fb_all_reports_download_v060123.py`. 

- This downloader would invoke an instance of the Chrome browser in headless mode. The code requires the chrome driver to run. I have downloaded the chrome driver from a mirror website. But no matter how I modify the directory path in code `driver = webdriver.Chrome(options=options, executable_path='/home/poleinikov/chromedriver')` , to run the chromedriver, the system would raise a path error: `TypeError: __init__() got an unexpected keyword argument 'executable_path'`. My solution is to add chromedriver to the environment variable, and modify the code to `driver = webdriver.Chrome()`

- After fixing this, I could successfully run the downloader, but it would raise the error: 

> DevTools listening on ws://127.0.0.1:10413/devtools/browser/86438e2e-d8a4-44fd-9543-093dddd806d5
> [13532:30168:0620/192301.860:ERROR:device_event_log_impl.cc(222)] [19:23:01.859] USB: usb_service_win.cc:415 Could not 
read device interface GUIDs: The system cannot find the file specified。 (0x2)

I could not find the solution to this issue; I am especially confused by how this error message suggests this might be a USB device recognition issue. But I think this might be an issue on my end. 

Other than that, the repos are very well organized. Especially the Readme is very in detail and precise. It helped me a lot when I ran the codes.

**Comment by sheoftensaid** [comment]
Here are our two logo options: 
<img src="https://mediaproject.wesleyan.edu/wp-content/uploads/2023/06/logo1.png" height="125">
<img src="https://mediaproject.wesleyan.edu/wp-content/uploads/2023/06/logo2.png" height="125">

**Comment by sheoftensaid** [comment]
I will digitize your icons in the next few days to share here, Candace!

**Comment by candace-walker** [comment]
@atlasharry  and I just met to talk about our ideas for the wireframe of the creative website. Here are some sketches of what we came up with: [Creative Wireframe.](https://docs.google.com/document/d/1OunRmLO-bEe47hFEBBxVP7yKkgBDvLzI8Qlqyws4Wd0/edit?usp=sharing) Let us know what you guys think and we could polish some things up.

**Comment by SebastianZimmeck** [comment]
That's good, @candace-walker and @atlasharry! 

Do you imagine one site with different sections (about etc.)? 

Also, I totally forgot. The [GPC landing page](https://globalprivacycontrol.org/) may be a good example.

**Comment by atlasharry** [comment]
Sorry for the late reply. I had some issues with my VPN yesterday.
Yes, we imagine a landing page with different icons, which can lead the user to different sections. For the different sections, one idea is to build different sub-pages. When the user clicks the icon, it will redirect them to a different page. Another approach is when the user clicks the icon; the site automatically scrolls down. In this case, the different sections are on the same page but require the user to scroll down to see.

**Comment by atlasharry** [comment]
We will try to refine this wireframe base on the reference to the GPC landing page!

**Comment by atlasharry** [comment]
![05aab48366a87eceb0090670306753a](https://github.com/Wesleyan-Media-Project/creative-app/assets/104949958/f9c69264-4076-4b72-80c9-8ebd0575f43a)
I have uploaded a refined version of how we imagine our landing page to be

**Comment by candace-walker** [comment]
I think we have decided on architecture design for the moment
